server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # ใช้ตอน docker compose (Ingress จะจับ /api ก่อนถึงตรงนี้ใน K8s)
    location /api/ {
        proxy_pass http://api:8000/;
    }
}
